name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@v1
        id: tagstep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install
      - run: npm run build

      - name: Replace version in files
        run: |
          sed -s -i "s/{VERSJON}/${{steps.tagstep.outputs.tag}}/g" dist/assets/*.js
        # uses: jostein-skaar/action-erstatninger@v1
        # with:
        #   sok: '{VERSJON}'
        #   erstatt: '${{steps.tagstep.outputs.tag}}'
        #   filer: 'dist/**/*.{js,html}'
        #   dry-run: false

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: www
          cname: vaktmesteren.fjaas.no
